### ISSUE TITLE
Some thing wrong

### ISSUE THREAD

**Issue by komorogrov** [fgsect/FitM#9]
I can't even start the program, so sad. But there are no errors in the make process

vagrant@ubuntu-focal:/vagrant$ FITM_ARGS=config/fitm-args.ftp.json make run
cargo build --release
sudo rm -rf ./active-state
sudo rm -rf ./cmin-tmp
sudo ./target/release/fitm config/fitm-args.ftp.json
sudo: ./target/release/fitm: command not found
make: *** [Makefile:40: run] Error 1

vagrant@ubuntu-focal:/vagrant$ ls
AFLplusplus  Makefile     config             debug            fitm.pdf     restore.sh.tmp  src
Cargo.toml   README.md    create_restore.py  fitm-qemu        libqasan.so  rpc.proto       tests
LICENSE      Vagrantfile  criu               fitm-qemu-trace  misc         rust-toolchain  tmp

**Comment by domenukk** [comment]
Sounds like FitM wasn't properly built (`make all`), or you are in the wrong folder?

**Comment by komorogrov** [comment]
Oh thanks, I finally succeed in Ubuntu 18.04.

**Comment by domenukk** [comment]
Great, thanks for the info :)
